# Generated by Django 5.1.15 on 2026-04-30 23:04

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogos", "0012_seed_implantes"),
        ("lotes", "0002_lotefusion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalReimplante",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Actualizado"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("fecha_aplicada", models.DateField(verbose_name="Fecha aplicada")),
                (
                    "numero",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Implante inicial"),
                            (1, "1er reimplante"),
                            (2, "2do reimplante"),
                            (3, "3er reimplante"),
                            (4, "4to reimplante"),
                        ],
                        default=0,
                        help_text="0 = implante inicial; 1-4 = reimplantes consecutivos.",
                    ),
                ),
                (
                    "peso_aplicado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Peso promedio del lote al momento del reimplante. Opcional.",
                        max_digits=6,
                        null=True,
                        verbose_name="Peso al aplicar (kg)",
                    ),
                ),
                (
                    "cabezas_aplicadas",
                    models.PositiveIntegerField(
                        help_text="Cuántas cabezas recibieron el implante.",
                        verbose_name="Cabezas aplicadas",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "implante",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalogos.implante",
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="lotes.lote",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Reimplante",
                "verbose_name_plural": "historical Reimplantes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Reimplante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creado")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Actualizado")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("fecha_aplicada", models.DateField(verbose_name="Fecha aplicada")),
                (
                    "numero",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Implante inicial"),
                            (1, "1er reimplante"),
                            (2, "2do reimplante"),
                            (3, "3er reimplante"),
                            (4, "4to reimplante"),
                        ],
                        default=0,
                        help_text="0 = implante inicial; 1-4 = reimplantes consecutivos.",
                    ),
                ),
                (
                    "peso_aplicado",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Peso promedio del lote al momento del reimplante. Opcional.",
                        max_digits=6,
                        null=True,
                        verbose_name="Peso al aplicar (kg)",
                    ),
                ),
                (
                    "cabezas_aplicadas",
                    models.PositiveIntegerField(
                        help_text="Cuántas cabezas recibieron el implante.",
                        verbose_name="Cabezas aplicadas",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "implante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalogos.implante"
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reimplantes",
                        to="lotes.lote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reimplante",
                "verbose_name_plural": "Reimplantes",
                "ordering": ["-fecha_aplicada", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("activo", True)),
                        fields=("lote", "numero"),
                        name="reimplante_unico_por_lote_y_numero",
                    )
                ],
            },
        ),
    ]
