# Generated by Django 5.1.15 on 2026-04-30 23:09

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lotes", "0002_lotefusion"),
        ("operacion", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EntradaZilpaterol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creado")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Actualizado")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("fecha_entrada", models.DateField()),
                ("observaciones", models.TextField(blank=True)),
                (
                    "lote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entrada_zilpaterol",
                        to="lotes.lote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada a Zilpaterol",
                "verbose_name_plural": "Entradas a Zilpaterol",
                "ordering": ["-fecha_entrada"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalEntradaZilpaterol",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Actualizado"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("fecha_entrada", models.DateField()),
                ("observaciones", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="lotes.lote",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Entrada a Zilpaterol",
                "verbose_name_plural": "historical Entradas a Zilpaterol",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTransicion",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Actualizado"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("fecha", models.DateField()),
                (
                    "de_fase",
                    models.CharField(
                        choices=[
                            ("F1", "F1"),
                            ("FT", "F1+F3 transición"),
                            ("F3", "F3"),
                            ("F3Z", "F3+Zilpaterol"),
                        ],
                        max_length=4,
                        verbose_name="De fase",
                    ),
                ),
                (
                    "a_fase",
                    models.CharField(
                        choices=[
                            ("F1", "F1"),
                            ("FT", "F1+F3 transición"),
                            ("F3", "F3"),
                            ("F3Z", "F3+Zilpaterol"),
                        ],
                        max_length=4,
                        verbose_name="A fase",
                    ),
                ),
                (
                    "proporcion",
                    models.CharField(blank=True, help_text="Ej: 50/50, 100% F3.", max_length=30),
                ),
                ("notas", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="lotes.lote",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Transición",
                "verbose_name_plural": "historical Transiciones",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Transicion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creado")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Actualizado")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("fecha", models.DateField()),
                (
                    "de_fase",
                    models.CharField(
                        choices=[
                            ("F1", "F1"),
                            ("FT", "F1+F3 transición"),
                            ("F3", "F3"),
                            ("F3Z", "F3+Zilpaterol"),
                        ],
                        max_length=4,
                        verbose_name="De fase",
                    ),
                ),
                (
                    "a_fase",
                    models.CharField(
                        choices=[
                            ("F1", "F1"),
                            ("FT", "F1+F3 transición"),
                            ("F3", "F3"),
                            ("F3Z", "F3+Zilpaterol"),
                        ],
                        max_length=4,
                        verbose_name="A fase",
                    ),
                ),
                (
                    "proporcion",
                    models.CharField(blank=True, help_text="Ej: 50/50, 100% F3.", max_length=30),
                ),
                ("notas", models.TextField(blank=True)),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transiciones",
                        to="lotes.lote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transición",
                "verbose_name_plural": "Transiciones",
                "ordering": ["-fecha", "-created_at"],
            },
        ),
    ]
