# Generated by Django 5.1.15 on 2026-04-30 23:18

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lotes", "0002_lotefusion"),
        ("operacion", "0002_entradazilpaterol_historicalentradazilpaterol_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPesaje",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Actualizado"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("fecha", models.DateField()),
                (
                    "peso_promedio",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Peso promedio (kg)"
                    ),
                ),
                (
                    "cabezas_pesadas",
                    models.PositiveIntegerField(
                        help_text="Si fue muestreo, este número puede ser menor que el inventario.",
                        verbose_name="Cabezas pesadas",
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="lotes.lote",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Pesaje",
                "verbose_name_plural": "historical Pesajes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Pesaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creado")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Actualizado")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("fecha", models.DateField()),
                (
                    "peso_promedio",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Peso promedio (kg)"
                    ),
                ),
                (
                    "cabezas_pesadas",
                    models.PositiveIntegerField(
                        help_text="Si fue muestreo, este número puede ser menor que el inventario.",
                        verbose_name="Cabezas pesadas",
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pesajes",
                        to="lotes.lote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pesaje",
                "verbose_name_plural": "Pesajes",
                "ordering": ["-fecha", "-created_at"],
            },
        ),
    ]
