# Generated by Django 5.1.15 on 2026-04-30 23:51

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0015_seed_formulas"),
        ("cierre", "0001_initial"),
        ("lotes", "0003_historicallote_cabezas_origen_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alimentacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creado")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Actualizado")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("kg_consumidos", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "costo_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Override del costo por kg. Si vacío, usa formula.costo_kg.",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                (
                    "formula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalogos.formula"
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alimentaciones",
                        to="lotes.lote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alimentación",
                "verbose_name_plural": "Alimentaciones",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalAlimentacion",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Actualizado"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("kg_consumidos", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "costo_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Override del costo por kg. Si vacío, usa formula.costo_kg.",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "formula",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalogos.formula",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="lotes.lote",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Alimentación",
                "verbose_name_plural": "historical Alimentaciones",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMedicacion",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Actualizado"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("recepcion", "Recepción / Metafilaxia"),
                            ("hospital", "Hospital"),
                        ],
                        default="recepcion",
                        max_length=12,
                    ),
                ),
                ("fecha", models.DateField()),
                ("cabezas", models.PositiveIntegerField(verbose_name="Cabezas tratadas")),
                (
                    "dosis_descripcion",
                    models.CharField(
                        blank=True, help_text="Ej: 2.5 ml/cab, 1 ml/10 kg.", max_length=60
                    ),
                ),
                (
                    "costo_unitario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Override del costo unitario. Si vacío, usa medicamento.costo_unitario.",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "arete",
                    models.CharField(blank=True, max_length=20, verbose_name="Arete (hospital)"),
                ),
                ("notas", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lote",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="lotes.lote",
                    ),
                ),
                (
                    "medicamento",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalogos.medicamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Medicación",
                "verbose_name_plural": "historical Medicaciones",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Medicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creado")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Actualizado")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("recepcion", "Recepción / Metafilaxia"),
                            ("hospital", "Hospital"),
                        ],
                        default="recepcion",
                        max_length=12,
                    ),
                ),
                ("fecha", models.DateField()),
                ("cabezas", models.PositiveIntegerField(verbose_name="Cabezas tratadas")),
                (
                    "dosis_descripcion",
                    models.CharField(
                        blank=True, help_text="Ej: 2.5 ml/cab, 1 ml/10 kg.", max_length=60
                    ),
                ),
                (
                    "costo_unitario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Override del costo unitario. Si vacío, usa medicamento.costo_unitario.",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "arete",
                    models.CharField(blank=True, max_length=20, verbose_name="Arete (hospital)"),
                ),
                ("notas", models.TextField(blank=True)),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="medicaciones",
                        to="lotes.lote",
                    ),
                ),
                (
                    "medicamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalogos.medicamento"
                    ),
                ),
            ],
            options={
                "verbose_name": "Medicación",
                "verbose_name_plural": "Medicaciones",
                "ordering": ["-fecha", "-created_at"],
            },
        ),
    ]
