# Generated by Django 5.1.15 on 2026-04-30 23:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cierre", "0002_alimentacion_historicalalimentacion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CostoHotelComponente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creado")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Actualizado")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("nombre", models.CharField(max_length=80, unique=True)),
                ("costo_dia_animal", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "habilitado",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcar si este componente ya se contabiliza en otra cuenta.",
                    ),
                ),
                ("notas", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Componente costo hotel",
                "verbose_name_plural": "Componentes costo hotel",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalCostoHotelComponente",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Actualizado"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("nombre", models.CharField(db_index=True, max_length=80)),
                ("costo_dia_animal", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "habilitado",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcar si este componente ya se contabiliza en otra cuenta.",
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Componente costo hotel",
                "verbose_name_plural": "historical Componentes costo hotel",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
