# Generated by Django 5.1.15 on 2026-04-30 22:16

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogos", "0010_seed_programa_reimplantes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalLote",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Actualizado"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "folio",
                    models.CharField(
                        db_index=True,
                        help_text="Editable manualmente. Único en el sistema.",
                        max_length=20,
                        verbose_name="Folio",
                    ),
                ),
                (
                    "cabezas_iniciales",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Cabezas iniciales",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de inicio")),
                (
                    "peso_inicial_promedio",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Peso inicial promedio (kg)"
                    ),
                ),
                (
                    "peso_salida_objetivo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Si vacío, se toma del programa aplicable.",
                        max_digits=6,
                        null=True,
                        verbose_name="Peso de salida objetivo (kg)",
                    ),
                ),
                (
                    "gdp_esperada",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Si vacío, se toma del programa aplicable.",
                        max_digits=4,
                        null=True,
                        verbose_name="GDP esperada (kg/día)",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "corral",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalogos.corral",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalogos.proveedor",
                    ),
                ),
                (
                    "tipo_ganado",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalogos.tipoganado",
                        verbose_name="Tipo de ganado",
                    ),
                ),
                (
                    "tipo_origen",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalogos.tipoorigen",
                        verbose_name="Tipo de origen",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Lote",
                "verbose_name_plural": "historical Lotes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Lote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creado")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Actualizado")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "folio",
                    models.CharField(
                        help_text="Editable manualmente. Único en el sistema.",
                        max_length=20,
                        unique=True,
                        verbose_name="Folio",
                    ),
                ),
                (
                    "cabezas_iniciales",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Cabezas iniciales",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de inicio")),
                (
                    "peso_inicial_promedio",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Peso inicial promedio (kg)"
                    ),
                ),
                (
                    "peso_salida_objetivo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Si vacío, se toma del programa aplicable.",
                        max_digits=6,
                        null=True,
                        verbose_name="Peso de salida objetivo (kg)",
                    ),
                ),
                (
                    "gdp_esperada",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Si vacío, se toma del programa aplicable.",
                        max_digits=4,
                        null=True,
                        verbose_name="GDP esperada (kg/día)",
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "corral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lotes",
                        to="catalogos.corral",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogos.proveedor",
                    ),
                ),
                (
                    "tipo_ganado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogos.tipoganado",
                        verbose_name="Tipo de ganado",
                    ),
                ),
                (
                    "tipo_origen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogos.tipoorigen",
                        verbose_name="Tipo de origen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote",
                "verbose_name_plural": "Lotes",
                "ordering": ["-fecha_inicio", "folio"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("activo", True)),
                        fields=("corral",),
                        name="lote_unico_activo_por_corral",
                    )
                ],
            },
        ),
    ]
