# Generated by Django 5.1.15 on 2026-04-30 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lotes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoteFusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creado")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Actualizado")),
                ("cabezas_movidas", models.PositiveIntegerField()),
                ("fecha_fusion", models.DateField()),
                ("notas", models.TextField(blank=True)),
                (
                    "lote_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fusiones_recibidas",
                        to="lotes.lote",
                    ),
                ),
                (
                    "lote_origen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fusiones_dadas",
                        to="lotes.lote",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fusión de lote",
                "verbose_name_plural": "Fusiones de lote",
                "ordering": ["-fecha_fusion", "-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("lote_destino", models.F("lote_origen")), _negated=True
                        ),
                        name="fusion_destino_distinto_de_origen",
                    )
                ],
            },
        ),
    ]
