# Generated by Django 5.1.15 on 2026-04-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lotes", "0002_lotefusion"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallote",
            name="cabezas_origen",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Cabezas embarcadas en el rancho/proveedor.",
                null=True,
                verbose_name="Cabezas en origen",
            ),
        ),
        migrations.AddField(
            model_name="historicallote",
            name="costo_compra",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Costo total de compra ($)",
            ),
        ),
        migrations.AddField(
            model_name="historicallote",
            name="fecha_compra",
            field=models.DateField(blank=True, null=True, verbose_name="Fecha de compra"),
        ),
        migrations.AddField(
            model_name="historicallote",
            name="kilos_origen",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Kilos en origen",
            ),
        ),
        migrations.AddField(
            model_name="historicallote",
            name="kilos_recibo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Kilos al desembarque en corral.",
                max_digits=10,
                null=True,
                verbose_name="Kilos en recibo",
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="cabezas_origen",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Cabezas embarcadas en el rancho/proveedor.",
                null=True,
                verbose_name="Cabezas en origen",
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="costo_compra",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Costo total de compra ($)",
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="fecha_compra",
            field=models.DateField(blank=True, null=True, verbose_name="Fecha de compra"),
        ),
        migrations.AddField(
            model_name="lote",
            name="kilos_origen",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Kilos en origen",
            ),
        ),
        migrations.AddField(
            model_name="lote",
            name="kilos_recibo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Kilos al desembarque en corral.",
                max_digits=10,
                null=True,
                verbose_name="Kilos en recibo",
            ),
        ),
    ]
