# Generated by Django 5.1.15 on 2026-04-30 05:04

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0003_tipoorigen_historicaltipoorigen"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creado")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Actualizado")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("nombre", models.CharField(max_length=120, unique=True, verbose_name="Nombre")),
                ("rfc", models.CharField(blank=True, max_length=13, verbose_name="RFC")),
                ("telefono", models.CharField(blank=True, max_length=20, verbose_name="Teléfono")),
                ("contacto", models.CharField(blank=True, max_length=80, verbose_name="Contacto")),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalProveedor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Actualizado"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("nombre", models.CharField(db_index=True, max_length=120, verbose_name="Nombre")),
                ("rfc", models.CharField(blank=True, max_length=13, verbose_name="RFC")),
                ("telefono", models.CharField(blank=True, max_length=20, verbose_name="Teléfono")),
                ("contacto", models.CharField(blank=True, max_length=80, verbose_name="Contacto")),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Proveedor",
                "verbose_name_plural": "historical Proveedores",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
