# Generated by Django 5.1.15 on 2026-04-30 13:46

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0005_corral_historicalcorral"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalProgramaReimplante",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Actualizado"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "peso_min",
                    models.DecimalField(decimal_places=2, max_digits=6, verbose_name="Peso mínimo"),
                ),
                (
                    "peso_max",
                    models.DecimalField(decimal_places=2, max_digits=6, verbose_name="Peso máximo"),
                ),
                (
                    "gdp_esperada",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="GDP esperada"
                    ),
                ),
                (
                    "peso_objetivo_salida",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Peso objetivo de salida"
                    ),
                ),
                (
                    "implante_inicial",
                    models.CharField(blank=True, max_length=40, verbose_name="Implante inicial"),
                ),
                (
                    "reimplante_1",
                    models.CharField(blank=True, max_length=40, verbose_name="1er reimplante"),
                ),
                (
                    "reimplante_2",
                    models.CharField(blank=True, max_length=40, verbose_name="2do reimplante"),
                ),
                (
                    "reimplante_3",
                    models.CharField(blank=True, max_length=40, verbose_name="3er reimplante"),
                ),
                (
                    "reimplante_4",
                    models.CharField(blank=True, max_length=40, verbose_name="4to reimplante"),
                ),
                (
                    "dias_recepcion",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Días recepción"),
                ),
                ("dias_f1", models.PositiveSmallIntegerField(default=0, verbose_name="Días F1")),
                (
                    "dias_transicion",
                    models.PositiveSmallIntegerField(default=14, verbose_name="Días transición"),
                ),
                ("dias_f3", models.PositiveSmallIntegerField(default=0, verbose_name="Días F3")),
                (
                    "dias_zilpaterol",
                    models.PositiveSmallIntegerField(default=35, verbose_name="Días Zilpaterol"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo_ganado",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalogos.tipoganado",
                        verbose_name="Tipo de ganado",
                    ),
                ),
                (
                    "tipo_origen",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Vacío = aplica a cualquier origen (caso vacas).",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalogos.tipoorigen",
                        verbose_name="Tipo de origen",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Programa de reimplante",
                "verbose_name_plural": "historical Programas de reimplante",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ProgramaReimplante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creado")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Actualizado")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "peso_min",
                    models.DecimalField(decimal_places=2, max_digits=6, verbose_name="Peso mínimo"),
                ),
                (
                    "peso_max",
                    models.DecimalField(decimal_places=2, max_digits=6, verbose_name="Peso máximo"),
                ),
                (
                    "gdp_esperada",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="GDP esperada"
                    ),
                ),
                (
                    "peso_objetivo_salida",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Peso objetivo de salida"
                    ),
                ),
                (
                    "implante_inicial",
                    models.CharField(blank=True, max_length=40, verbose_name="Implante inicial"),
                ),
                (
                    "reimplante_1",
                    models.CharField(blank=True, max_length=40, verbose_name="1er reimplante"),
                ),
                (
                    "reimplante_2",
                    models.CharField(blank=True, max_length=40, verbose_name="2do reimplante"),
                ),
                (
                    "reimplante_3",
                    models.CharField(blank=True, max_length=40, verbose_name="3er reimplante"),
                ),
                (
                    "reimplante_4",
                    models.CharField(blank=True, max_length=40, verbose_name="4to reimplante"),
                ),
                (
                    "dias_recepcion",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Días recepción"),
                ),
                ("dias_f1", models.PositiveSmallIntegerField(default=0, verbose_name="Días F1")),
                (
                    "dias_transicion",
                    models.PositiveSmallIntegerField(default=14, verbose_name="Días transición"),
                ),
                ("dias_f3", models.PositiveSmallIntegerField(default=0, verbose_name="Días F3")),
                (
                    "dias_zilpaterol",
                    models.PositiveSmallIntegerField(default=35, verbose_name="Días Zilpaterol"),
                ),
                (
                    "tipo_ganado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogos.tipoganado",
                        verbose_name="Tipo de ganado",
                    ),
                ),
                (
                    "tipo_origen",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vacío = aplica a cualquier origen (caso vacas).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogos.tipoorigen",
                        verbose_name="Tipo de origen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programa de reimplante",
                "verbose_name_plural": "Programas de reimplante",
                "ordering": ["tipo_ganado__nombre", "tipo_origen__nombre", "peso_min"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("peso_max__gt", models.F("peso_min"))),
                        name="programa_peso_max_gt_min",
                    )
                ],
            },
        ),
    ]
