# Generated by Django 5.1.15 on 2026-04-30 23:51

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0013_seed_potrero"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Formula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creado")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Actualizado")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("nombre", models.CharField(max_length=60, unique=True)),
                (
                    "costo_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Costo por kg ($)",
                    ),
                ),
                ("notas", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Fórmula",
                "verbose_name_plural": "Fórmulas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Medicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Creado")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Actualizado")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("nombre", models.CharField(max_length=80, unique=True)),
                ("principio_activo", models.CharField(blank=True, max_length=120)),
                (
                    "unidad_dosis",
                    models.CharField(
                        choices=[
                            ("ml/cab", "ml por cabeza"),
                            ("ml/kg", "ml por kg de peso"),
                            ("dosis", "dosis fija"),
                        ],
                        default="ml/cab",
                        max_length=10,
                    ),
                ),
                (
                    "costo_unitario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Costo por unidad (ml, dosis, etc.).",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Medicamento",
                "verbose_name_plural": "Medicamentos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalFormula",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Actualizado"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("nombre", models.CharField(db_index=True, max_length=60)),
                (
                    "costo_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Costo por kg ($)",
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Fórmula",
                "verbose_name_plural": "historical Fórmulas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMedicamento",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, verbose_name="Actualizado"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("nombre", models.CharField(db_index=True, max_length=80)),
                ("principio_activo", models.CharField(blank=True, max_length=120)),
                (
                    "unidad_dosis",
                    models.CharField(
                        choices=[
                            ("ml/cab", "ml por cabeza"),
                            ("ml/kg", "ml por kg de peso"),
                            ("dosis", "dosis fija"),
                        ],
                        default="ml/cab",
                        max_length=10,
                    ),
                ),
                (
                    "costo_unitario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Costo por unidad (ml, dosis, etc.).",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Medicamento",
                "verbose_name_plural": "historical Medicamentos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
